schema:                http                  # support http and https
port:                  8000                    # port for balancer
ssl_certificate:
ssl_certificate_key:
tcp_health_check:      true
health_check_interval: 3      # health check interval (second)
# The maximum number of requests that the balancer can handle at the same time
# 0 refers to no limit to the maximum number of requests
max_allowed:           100
location: # route matching for reverse proxy
  - pattern:      /
    proxy_pass: # URL of the reverse proxy
      - "http://127.0.0.1:8080"
      - "http://127.0.0.1:8081"
      - "http://127.0.0.1:8082"
      - "http://127.0.0.1:8083"
      - "http://127.0.0.1:8084"
    balance_mode: round-robin     # load balancing algorithm
    
  - pattern: /random
    proxy_pass:
      - "http://127.0.0.1:8082"
      - "http://127.0.0.1:8083"
      - "http://127.0.0.1:8084"
    balance_mode: random